
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: nextcloud_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - VIRTUAL_HOST=phpmyadmin.localhost
    depends_on:
      - db
    networks:
      - proxy-tier
